# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aad909bb3c7c11a2ea15b33227c53e956c758579e99706ff7cf08daec40555841ab4e217b9648946a4ae72346992894f9ded9cb76d5755bb9bb338835f015f60

test:
  secret_key_base: 84e0418757acce2e744e8c980e914d56055827a6edd12bbd6f59770ace2b1583b7c246a9ba131a3ec6c0c01f207528aac508d6c705b08db9e11f3169217f69aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
